version: '3.8'

services:
  db_tercer_modulo:
    image: postgres:15.1
    restart: always
    environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_DB=${PGDATABASE}
    ports:
      - '${PGPORT}:5432'
    volumes:
      - ./db_tercer_modulo:/var/lib/postgresql/data